services:
        mysql-8:
                image: mysql:8.0.32
                environment:
                        MYSQL_ROOT_PASSWORD: Admin123@
                        MYSQL_DATABASE: Exercicio
                        MYSQL_USER: admin
                        MYSQL_PASSWORD: admin
                ports:
                        - 3306:3306
                expose:
                        - 3306
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost:3306"]
                        interval: 30s
                        timeout: 10s
                        retries: 5        
                
        rabbitmq:
                image: rabbitmq:3.11.11-management
                container_name: rabbitmq
                ports:
                        - "5672:5672"
                        - "15672:15672"
                volumes:
                        - ./dados:/var/lib/rabbitmq/
                environment:
                        - RABBITMQ_DEFAULT_USER=rabbitmq
                
                        - RABBITMQ_DEFAULT_PASS=rabbitmq
                healthcheck:
                        test: rabbitmq-diagnostics -q ping
                        interval: 30s
                        timeout: 10s
                        retries: 10
                        start_period: 30s
                        
        app-principal:
                build:
                        context: ./APIPRINCIPAL
                        dockerfile: Dockerfile-api1
                depends_on:
                        mysql-8:
                                      condition: service_healthy
                        rabbitmq:
                                      condition: service_healthy
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-8:3306/Exercicio?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
                        SPRING_DATASOURCE_USERNAME: admin
                        SPRING_DATASOURCE_PASSWORD: admin
                        SPRING_RABBITMQ_HOST: rabbitmq
                        
                ports:
                        - "8080:8080"
        app-mock:
                build:
                        context: ./mockapi
                        dockerfile: Dockerfile-api2                
                depends_on:
              
                        rabbitmq:
                        
                                      condition: service_healthy               
                environment:
                        SPRING_RABBITMQ_HOST: rabbitmq
                 
       
